remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
tite: My GitHub Pages Skills Work
author: Joshua Armstrong
description: This is the GitHub Pages that I work on to learn to use GitHub pages better for my customers.
